# Generated by Django 2.2.24 on 2021-07-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200)),
                ('nationalID', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('dicomImg', models.FileField(upload_to='dicom')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
