# Generated by Django 2.2.24 on 2021-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='modality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
